name: exam_score_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - dagshub
      - scikit-learn
      - pandas
      - numpy
      - joblib
      - matplotlib
      - setuptools